name: Docker Build and Publish

on:
    push:
        branches: [ main ]
        tags: [ 'v*' ]
    pull_request:
        branches: [ main ]

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v3
              
            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                # list of Docker images to use as base name for tags
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                flavor: |
                  latest=auto
                # generate Docker tags based on the following events/attributes
                tags: |
                  type=schedule
                  type=ref,event=branch
                  type=ref,event=pr
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
                  type=sha
                  type=ref,event=tag

            - name: "Set up Docker Buildx"
              uses: docker/setup-buildx-action@v3

            - name: "Log in to the Container registry"
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v3
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: "Build and push Docker image"
              uses: docker/build-push-action@v6
              with:
                context: .
                push: ${{ github.event_name != 'pull_request' }}
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                #cache-from: type=gha
                #cache-to: type=gha,mode=max